package com.simbirsoft.pages;

import com.codeborne.selenide.Condition;
import com.codeborne.selenide.SelenideElement;

import static com.codeborne.selenide.Selectors.byText;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$x;

public class AdvancedSearchPage {

    private SelenideElement boldHeader = $(".bloko-header-1");
    private SelenideElement keywordField = $x("//*[@data-qa='vacancysearch__keywords-input']");
    private SelenideElement vacancyNameCheckbox = $(byText("в названии вакансии")).parent();
    private SelenideElement companyNameCheckbox = $(byText("в названии вакансии")).parent();
    private SelenideElement vacancyDescriptionCheckbox = $(byText("в названии вакансии")).parent();
    private SelenideElement searchLanguageDescriptionLink = $(byText("Описание языка поисковых запросов")).parent();
    private SelenideElement specializations = $(byText("Указать специализации")).preceding(0);
    private SelenideElement selectSpecializationsLink = $x("//*[@data-qa='resumesearch__profroles-switcher']");
    private SelenideElement industry = $(byText("Указать отрасль компании")).preceding(0).$("HH-Employer-Industries-ShowIfZeroFields");
    private SelenideElement selectIndustryLink = $x("//*[@data-qa='industry-addFromList']");
    private SelenideElement regionSearchField = $x("//*[@data-qa='resumes-search-region-add']");
    private SelenideElement salaryNumberField = $x("//*[@data-qa='vacancysearch__compensation-input']");
    private SelenideElement salaryCurrencyField = $x("//*[@data-qa='vacancysearch__compensation-currency']");
    private SelenideElement searchOnlySetSalaryCheckbox = $x("//*[@data-qa='vacancysearch__only-with-compensation']");
    private SelenideElement experienceDoesNotMatterRadiobutton = $x("//*[@data-qa='vacancysearch__experience-item_doesNotMatter']");
    private SelenideElement noExperienceRadiobutton = $x("//*[@data-qa='vacancysearch__experience-item_doesNotMatter']");
    private SelenideElement oneToThreeYearsExperienceRadiobutton = $x("//*[@data-qa='vacancysearch__experience-item_doesNotMatter']");
    private SelenideElement threeToSixYearsExperienceRadiobutton = $x("//*[@data-qa='vacancysearch__experience-item_doesNotMatter']");
    private SelenideElement moreThanSixYearsExperienceRadiobutton = $x("//*[@data-qa='vacancysearch__experience-item_doesNotMatter']");
    private SelenideElement fullTimeEmploymentCheckbox = $x("//*[@data-qa='vacancysearch__employment-item_full']");
    private SelenideElement partTimeEmploymentCheckbox = $x("//*[@data-qa='vacancysearch__employment-item_part']");
    private SelenideElement projectEmploymentCheckbox = $x("//*[@data-qa='vacancysearch__employment-item_project']");
    private SelenideElement volunteerEmploymentCheckbox = $x("//*[@data-qa='vacancysearch__employment-item_volunteer']");
    private SelenideElement internshipEmploymentCheckbox = $x("//*[@data-qa='vacancysearch__employment-item_probation']");
    private SelenideElement fullDayWorkHoursCheckbox = $x("//*[@data-qa='vacancysearch__schedule-item_fullDay']");
    private SelenideElement shiftWorkHoursCheckbox = $x("//*[@data-qa='vacancysearch__schedule-item_shift']");
    private SelenideElement flexibleWorkHoursCheckbox = $x("//*[@data-qa='vacancysearch__schedule-item_flexible']");
    private SelenideElement remoteWorkHoursCheckbox = $x("//*[@data-qa='vacancysearch__schedule-item_remote']");
    private SelenideElement flyInFlyOutWorkCheckbox = $x("//*[@data-qa='vacancysearch__schedule-item_flyInFlyOut']");
    private SelenideElement hideAgencyVacanciesOptionCheckbox = $x("//*[@data-qa='vacancysearch__hide-agenсies_not_from_agency']");
    private SelenideElement hideNotAvailableForDisabledOptionCheckbox = $x("//*[@data-qa='vacancysearch__only-for-disabled_accept_handicapped']");
    private SelenideElement showOnlyAvailableForUnderagedOptionCheckbox = $x("//*[@data-qa='vacancysearch__only-for-kids_accept_kids']");
    private SelenideElement sortByRelevanceRadiobutton = $x("//*[@data-qa='search__order_relevance']");
    private SelenideElement sortByUpdatedRadiobutton = $x("//*[@data-qa='search__order_publication_time']");
    private SelenideElement sortBySalaryDescendingRadiobutton = $x("//*[@data-qa='search__order_salary_desc']");
    private SelenideElement sortBySalaryAscendingRadiobutton = $x("//*[@data-qa='search__order_salary_asc']");
    private SelenideElement filterAllTimeRadiobutton = $x("//*[@data-qa='vacancysearch__searchperiod-item_0']");
    private SelenideElement filterMonthRadiobutton = $x("//*[@data-qa='vacancysearch__searchperiod-item_30']");
    private SelenideElement filterWeekRadiobutton = $x("//*[@data-qa='vacancysearch__searchperiod-item_7']");
    private SelenideElement filterThreeDaysRadiobutton = $x("//*[@data-qa='vacancysearch__searchperiod-item_3']");
    private SelenideElement filterOneDayRadiobutton = $x("//*[@data-qa='vacancysearch__searchperiod-item_1']");
    private SelenideElement showTwentyRadiobutton = $x("//*[@data-qa='search__items-on-page_20']");
    private SelenideElement showFiftyRadiobutton = $x("//*[@data-qa='search__items-on-page_50']");
    private SelenideElement showHundredRadiobutton = $x("//*[@data-qa='search__items-on-page_100']");
    private SelenideElement submitButton = $("#submit-bottom");

    public AdvancedSearchPage checkPresenceOfVitalElements() {
        boldHeader.shouldBe(Condition.visible);
        keywordField.shouldBe(Condition.visible);
        vacancyNameCheckbox.shouldBe(Condition.visible);
        companyNameCheckbox.shouldBe(Condition.visible);
        vacancyDescriptionCheckbox.shouldBe(Condition.visible);
        searchLanguageDescriptionLink.shouldBe(Condition.visible);
        specializations.shouldBe(Condition.visible);
        selectSpecializationsLink.shouldBe(Condition.visible);
        industry.shouldBe(Condition.visible);
        selectIndustryLink.shouldBe(Condition.visible);
        regionSearchField.shouldBe(Condition.visible);
        salaryNumberField.shouldBe(Condition.visible);
        salaryCurrencyField.shouldBe(Condition.visible);
        searchOnlySetSalaryCheckbox.shouldBe(Condition.visible);
        experienceDoesNotMatterRadiobutton.shouldBe(Condition.visible);
        noExperienceRadiobutton.shouldBe(Condition.visible);
        oneToThreeYearsExperienceRadiobutton.shouldBe(Condition.visible);
        threeToSixYearsExperienceRadiobutton.shouldBe(Condition.visible);
        moreThanSixYearsExperienceRadiobutton.shouldBe(Condition.visible);
        fullTimeEmploymentCheckbox.shouldBe(Condition.visible);
        partTimeEmploymentCheckbox.shouldBe(Condition.visible);
        projectEmploymentCheckbox.shouldBe(Condition.visible);
        internshipEmploymentCheckbox.shouldBe(Condition.visible);
        fullDayWorkHoursCheckbox.shouldBe(Condition.visible);
        shiftWorkHoursCheckbox.shouldBe(Condition.visible);
        flexibleWorkHoursCheckbox.shouldBe(Condition.visible);
        remoteWorkHoursCheckbox.shouldBe(Condition.visible);
        flyInFlyOutWorkCheckbox.shouldBe(Condition.visible);
        hideAgencyVacanciesOptionCheckbox.shouldBe(Condition.visible);
        hideNotAvailableForDisabledOptionCheckbox.shouldBe(Condition.visible);
        showOnlyAvailableForUnderagedOptionCheckbox.shouldBe(Condition.visible);
        sortByRelevanceRadiobutton.shouldBe(Condition.visible);
        sortByUpdatedRadiobutton.shouldBe(Condition.visible);
        sortBySalaryDescendingRadiobutton.shouldBe(Condition.visible);
        sortBySalaryAscendingRadiobutton.shouldBe(Condition.visible);
        filterAllTimeRadiobutton.shouldBe(Condition.visible);
        filterMonthRadiobutton.shouldBe(Condition.visible);
        filterWeekRadiobutton.shouldBe(Condition.visible);
        filterThreeDaysRadiobutton.shouldBe(Condition.visible);
        filterOneDayRadiobutton.shouldBe(Condition.visible);
        showTwentyRadiobutton.shouldBe(Condition.visible);
        showFiftyRadiobutton.shouldBe(Condition.visible);
        showHundredRadiobutton.shouldBe(Condition.visible);
        submitButton.shouldBe(Condition.visible);
        return this;
    }
}
